import Foundation

struct ScriptOptions {
    var verifySignatures = true
    var strictVerify = false      // when true, a bad signature aborts that item
    var skipInstalled = true
    var installToUserApplications = false
    var logPath = "/tmp/macsetup.log"
    /// Touch this file to pause the run between items; delete it to resume.
    var pausePath = "/tmp/macsetup.pause"
    /// Seconds to leave the authorisation dialog up before giving up. Zero
    /// means wait indefinitely, which is right when someone is sitting there
    /// and wrong for a scheduled run.
    var authTimeout = 0
    /// Web apps as real standalone applications rather than browser launchers.
    var standaloneWebApps = false
}

enum ScriptGenerator {

    /// Builds a script that installs the given Apple updates, through the same
    /// elevated batch as everything else.
    static func buildSystemUpdates(_ updates: [SystemUpdate],
                                   options: ScriptOptions = ScriptOptions()) -> String {
        var out = """
        #!/bin/bash
        #
        #  Generated by MacSetup — Apple software updates
        #
        #  Installs \(updates.count) update(s) with softwareupdate, behind one
        #  administrator prompt. A restart is never triggered here: anything
        #  marked as needing one is staged, and macOS will ask when you are ready.
        #

        """
        for u in updates {
            out += "#    - \(u.title) \(u.version)\(u.requiresRestart ? "   [needs a restart]" : "")\n"
        }
        out += "\n"
        out += config(options: options, arch: .current, forUninstall: true)
        out += ScriptPrelude.body
        out += "\n# ====================================================== apple updates\n"
        out += "msu_status \"__queue__\" begin \"\(updates.count)\"\n\n"
        for u in updates {
            out += "msu_begin \(sh(u.label))\n"
            out += "msu_queue_system \(sh(u.label)) \(sh(u.label))\n"
        }
        out += "\nmsu_flush_pkgs\n"
        out += footer()
        return out
    }

    /// Builds a script that removes the given targets.
    static func buildUninstall(targets: [UninstallTarget],
                               options: ScriptOptions = ScriptOptions()) -> String {
        var out = """
        #!/bin/bash
        #
        #  Generated by MacSetup — UNINSTALL
        #
        #  Moves \(targets.count) application bundle(s) to the Trash, or removes them
        #  through Homebrew where that is how they were installed. Preferences,
        #  licences and user data are left alone, and nothing is deleted outright.
        #

        """
        for t in targets { out += "#    - \(t.name)\n" }
        out += "\n"
        out += config(options: options, arch: .current, forUninstall: true)
        out += ScriptPrelude.body
        out += "\n# ============================================================= uninstall\n"
        out += "msu_status \"__queue__\" begin \"\(targets.count)\"\n\n"
        for t in targets {
            out += "msu_wait_if_paused\n"
            out += "msu_uninstall \(sh(t.id)) \(sh(t.name)) \(sh(t.bundleID)) \(sh(t.kind)) \(sh(t.token))\n"
        }
        out += footer()
        return out
    }

    static func buildUninstall(apps: [CatalogApp], options: ScriptOptions = ScriptOptions()) -> String {
        buildUninstall(targets: apps.map(UninstallTarget.init), options: options)
    }

    /// Builds the complete, self-contained bash script for a run.
    static func build(apps: [CatalogApp],
                      tweaks: [DefaultTweak],
                      webApps: [WebApp] = [],
                      systemUpdates: [SystemUpdate] = [],
                      stagedUpdates: [SystemUpdate] = [],
                      browser: BrowserInfo? = nil,
                      options: ScriptOptions = ScriptOptions(),
                      arch: Arch = .current) -> String {

        var out = header(apps: apps, tweaks: tweaks, webApps: webApps,
                         browser: browser, arch: arch, options: options)
        out += config(options: options, arch: arch)
        out += ScriptPrelude.body
        out += "\n# ================================================================ queue\n"
        out += "msu_receipt_init\n"
        out += "msu_status \"__queue__\" begin \"\(apps.count + tweaks.count + webApps.count + systemUpdates.count + stagedUpdates.count)\"\n\n"

        // Packages first: they are the only items that need a password, so the
        // authorisation dialog appears near the start of the run rather than
        // after every other download has completed.
        let needsAuth: (CatalogApp) -> Bool = {
            $0.source.needsRoot || $0.isBrewPackage || $0.needsTerminal
        }
        let packaged = apps.filter(needsAuth)
        let rest = apps.filter { !needsAuth($0) }

        // Apple updates need the same authorisation, so they join the same batch
        // and the user is asked once for the whole run.
        if !packaged.isEmpty || !systemUpdates.isEmpty || !stagedUpdates.isEmpty {
            out += "# ---- items needing administrator authorisation --------------------\n"
            for app in packaged { out += job(for: app, options: options) }
            for u in systemUpdates {
                out += "msu_wait_if_paused\n"
                out += "msu_begin \(sh(u.label))\n"
                out += "msu_queue_system \(sh(u.label)) \(sh(u.label))\n"
            }
            // Downloaded now, installed when someone is at the machine.
            for u in stagedUpdates {
                out += "msu_wait_if_paused\n"
                out += "msu_begin \(sh(u.label))\n"
                out += "msu_queue_system_download \(sh(u.label)) \(sh(u.label))\n"
            }
            out += "\nmsu_flush_pkgs\n\n"
        }
        for app in rest { out += job(for: app, options: options) }
        // A fallback to Homebrew can still queue a package, so flush again.
        if !rest.isEmpty { out += "\nmsu_flush_pkgs\n" }
        if !webApps.isEmpty, let browser {
            out += webAppSection(webApps, browser: browser, standalone: options.standaloneWebApps)
        }
        if !tweaks.isEmpty { out += defaultsSection(tweaks) }
        out += footer()
        return out
    }

    // MARK: - Sections

    private static func header(apps: [CatalogApp], tweaks: [DefaultTweak],
                               webApps: [WebApp], browser: BrowserInfo?, arch: Arch,
                               options: ScriptOptions) -> String {
        let stamp = ISO8601DateFormatter().string(from: Date())
        var s = """
        #!/bin/bash
        #
        #  Generated by MacSetup on \(stamp)
        #  Target architecture: \(arch.rawValue) (\(arch.display))
        #
        #  \(apps.count) application(s), \(webApps.count) web app(s), \(tweaks.count) system tweak(s).
        #  Every download below comes from the vendor's own servers or from
        #  Homebrew. Review it before running if you like — it is plain bash.
        #

        """
        for a in apps { s += "#    - \(a.name)  [\(a.source.shortLabel)]\n" }
        if let browser, !webApps.isEmpty {
            if webApps.isEmpty == false, options.standaloneWebApps, webAppHostPath != nil {
                s += "#\n#  Web apps are built as standalone applications (own Dock icon,\n"
                s += "#  own window, separate sign-in from \(browser.name)).\n"
            } else {
                s += "#\n#  Web apps open in \(browser.name)"
                s += browser.supportsAppMode ? " using --app= (own window).\n" : " as ordinary windows.\n"
            }
            for w in webApps { s += "#    @ \(w.name)  \(w.url)\n" }
        }
        for t in tweaks { s += "#    * \(t.name)\n" }
        return s + "\n"
    }

    private static func config(options: ScriptOptions, arch: Arch,
                               forUninstall: Bool = false) -> String {
        let home = NSHomeDirectory()
        let user = NSUserName()
        let appDir = options.installToUserApplications ? "\(home)/Applications" : "/Applications"
        return """
        set -uo pipefail

        # A GUI-launched shell does not necessarily inherit /usr/sbin, and
        # `do shell script` gives the elevated child an even barer environment.
        # codesign, pkgutil, spctl and installer all live there, so set it
        # explicitly rather than hoping.
        export PATH="/usr/bin:/bin:/usr/sbin:/sbin${PATH:+:$PATH}"

        REAL_USER=\(sh(user))
        USER_HOME=\(sh(home))
        MSU_ARCH=\(sh(arch.rawValue))
        APPDIR=\(sh(appDir))
        LOG=\(sh(options.logPath))
        PAUSE_FLAG=\(sh(options.pausePath))
        VERIFY=\(options.verifySignatures ? "1" : "0")
        STRICT_VERIFY=\(options.strictVerify ? "1" : "0")
        \(forUninstall ? "" : "SKIP_INSTALLED=\(options.skipInstalled ? "1" : "0")")
        BREW_BIN=""
        MSU_HANDOFF="$HOME/Library/Caches/MacSetup/handoff"
        OPEN_TERMINAL=1
        MSU_AUTH_TIMEOUT=\(options.authTimeout)
        MSU_UA="MacSetup/1.0 (+macOS installer)"

        STAGE=$(mktemp -d /tmp/macsetup.stage.XXXXXX)
        PKG_QUEUE="$STAGE/pkgs.tsv"
        : > "$PKG_QUEUE"
        mkdir -p "$APPDIR"



        """
    }

    /// One app becomes: skip-check, primary attempt, optional Homebrew fallback.
    private static func job(for app: CatalogApp, options: ScriptOptions) -> String {
        let id = sh(app.id)
        let name = sh(app.name)
        let bundle = sh(app.bundleId ?? "")
        let team = sh(app.teamId ?? "")

        var s = "# ---- \(app.name) ------------------------------------------------\n"
        s += "msu_wait_if_paused\n"
        s += "msu_begin \(id)\n"

        if options.skipInstalled, app.bundleId != nil || app.source.kind != .brew {
            s += "if [ \"$SKIP_INSTALLED\" = \"1\" ] && msu_installed \(bundle) \(name); then\n"
            s += "  msu_skip \(id)\n"
            s += "else\n"
        } else {
            s += "if false; then :\nelse\n"
        }

        s += "  \(attempt(app.source, app: app, team: team)); MSU_RC=$?\n"
        s += "  if [ $MSU_RC -eq 0 ]; then\n"
        s += "    msu_ok \(id)\n"
        s += "    msu_receipt \(id) \(name) installed \"\" \(bundle)\n"
        s += "  elif [ $MSU_RC -eq 3 ]; then\n"
        s += "    :   # queued for the elevated package batch; status follows later\n"
        s += "  elif [ $MSU_RC -eq 2 ]; then\n"
        s += "    msu_fail \(id)   # signature check failed, not falling back\n"
        if let fb = app.fallback {
            s += "  elif msu_status \(id) retry \"$MSU_ERR — trying Homebrew\" && \(attempt(fb, app: app, team: team)); then\n"
            s += "    msu_ok \(id) \"Installed via Homebrew\"\n"
        }
        s += "  else\n"
        s += "    msu_fail \(id)\n"
        s += "    msu_receipt \(id) \(name) failed \"$MSU_ERR\" \(bundle)\n"
        s += "  fi\n"
        s += "fi\n\n"
        return s
    }

    static func attempt(_ src: AppSource, app: CatalogApp, team: String) -> String {
        let id = sh(app.id)
        switch src.kind {
        case .direct:
            guard let url = src.resolvedURL(arch: .current) else {
                return "false"
            }
            return "msu_try_direct \(id) \(sh(url)) \(sh(src.format ?? "dmg")) \(team)"
        case .github:
            return "msu_try_github \(id) \(sh(src.repo ?? "")) \(sh(src.assetPattern ?? ".")) \(sh(src.format ?? "dmg")) \(team)"
        case .brew:
            if let cask = src.cask {
                // A .pkg cask goes through fetch + the elevated batch, so it
                // works from the app instead of demanding a terminal.
                if src.cask == app.source.cask {
                    if app.needsTerminal {
                        // Runs its own installer: fetch with Homebrew, verify,
                        // then execute it inside the elevated batch.
                        return "msu_brew_installer_run \(id) \(sh(cask)) \(team)"
                    }
                    if app.isBrewPackage {
                        return "msu_brew_pkg_install \(id) \(sh(cask)) \(team)"
                    }
                }
                return "msu_brew_install \(id) \(sh(cask)) cask"
            }
            return "msu_brew_install \(id) \(sh(src.formula ?? "")) formula"
        case .script:
            let env = (src.env ?? [:]).map { "\(sh("\($0.key)=\($0.value)"))" }.joined(separator: " ")
            return "msu_try_script \(id) \(sh(src.url ?? "")) \(sh(src.verify ?? "")) \(env)"
        }
    }

    /// The embedded host binary, when this copy of MacSetup ships one.
    static var webAppHostPath: String? {
        if let res = Bundle.main.resourceURL?.appendingPathComponent("WebAppHost").path,
           FileManager.default.isExecutableFile(atPath: res) { return res }
        let beside = URL(fileURLWithPath: CommandLine.arguments[0])
            .deletingLastPathComponent().appendingPathComponent("WebAppHost").path
        if FileManager.default.isExecutableFile(atPath: beside) { return beside }
        return nil
    }

    private static func webAppSection(_ webApps: [WebApp], browser: BrowserInfo,
                                      standalone: Bool) -> String {
        var s = "\n# ============================================================== web apps\n"
        let exe = browser.supportsAppMode ? browser.executablePath : browser.name
        let host = standalone ? (webAppHostPath ?? "") : ""
        for w in webApps {
            s += "msu_wait_if_paused\n"
            s += "msu_begin \(sh(w.id))\n"
            s += "if msu_make_webapp \(sh(w.id)) \(sh(w.name)) \(sh(w.url)) \(sh(exe)) "
            s += "\(browser.supportsAppMode ? "1" : "0") \(sh(w.icon ?? "")) \(sh(browser.name)) \(sh(host)); then\n"
            s += "  msu_ok \(sh(w.id)) \(sh("Created in \(browser.name)"))\n"
            s += "  msu_receipt \(sh(w.id)) \(sh(w.name)) installed \"web app\" \"\"\n"
            s += "else\n"
            s += "  msu_fail \(sh(w.id))\n"
            s += "  msu_receipt \(sh(w.id)) \(sh(w.name)) failed \"$MSU_ERR\" \"\"\n"
            s += "fi\n"
        }
        return s
    }

    private static func defaultsSection(_ tweaks: [DefaultTweak]) -> String {
        var s = "\n# ================================================ macOS system defaults\n"
        var restarts = Set<String>()
        for t in tweaks {
            s += "msu_wait_if_paused\n"
            s += "msu_begin \(sh(t.id))\n"
            s += "if msu_as_user /bin/bash -c \(sh(t.command)) >>\"$LOG\" 2>&1; then\n"
            s += "  msu_ok \(sh(t.id)) \"Applied\"\n"
            s += "  msu_receipt \(sh(t.id)) \(sh(t.name)) applied \"tweak\" \"\"\n"
            s += "else\n"
            s += "  msu_fail \(sh(t.id)) \"Could not apply this setting\"\n"
            s += "  msu_receipt \(sh(t.id)) \(sh(t.name)) failed \"tweak\" \"\"\n"
            s += "fi\n"
            restarts.formUnion(t.restart)
        }
        if !restarts.isEmpty {
            s += "\n# Restart the affected UI services so the changes take effect now.\n"
            for r in restarts.sorted() {
                s += "msu_as_user killall \(sh(r)) >/dev/null 2>&1 || true\n"
            }
        }
        return s
    }

    private static func footer() -> String {
        """

        # ================================================================ summary
        msu_status "__queue__" finished "$MSU_OK|$MSU_FAIL|$MSU_SKIP"
        printf '\\n──────────────────────────────────────────────\\n'
        printf ' Installed: %s   Failed: %s   Skipped: %s\\n' "$MSU_OK" "$MSU_FAIL" "$MSU_SKIP"
        printf '──────────────────────────────────────────────\\n'
        exit 0

        """
    }

    /// Jamf runs as root, so /Applications is writable and no elevation dance
    /// is needed; the console user is still used for anything user-scoped.
    static func configForJamf(options: ScriptOptions) -> String {
        """
        REAL_USER=$(/usr/bin/stat -f%Su /dev/console)
        USER_HOME=$(/usr/bin/dscl . -read "/Users/$REAL_USER" NFSHomeDirectory 2>/dev/null | awk '{print $2}')
        USER_HOME="${USER_HOME:-/Users/$REAL_USER}"
        MSU_ARCH=$(/usr/bin/uname -m)
        APPDIR=/Applications
        LOG=\(sh(options.logPath))
        PAUSE_FLAG=/tmp/macsetup.pause.jamf
        VERIFY=\(options.verifySignatures ? "1" : "0")
        STRICT_VERIFY=\(options.strictVerify ? "1" : "0")
        SKIP_INSTALLED=0
        BREW_BIN=""
        MSU_HANDOFF="$HOME/Library/Caches/MacSetup/handoff"
        OPEN_TERMINAL=1
        MSU_AUTH_TIMEOUT=\(options.authTimeout)
        MSU_UA="MacSetup/1.0 (+managed)"

        STAGE=$(mktemp -d /tmp/macsetup.stage.XXXXXX)
        PKG_QUEUE="$STAGE/pkgs.tsv"
        : > "$PKG_QUEUE"


        """
    }

    /// Under Jamf we are already root, so packages install inline — there is no
    /// authorisation prompt to batch behind.
    static func jamfJob(for app: CatalogApp) -> String {
        let id = sh(app.id), name = sh(app.name), bundle = sh(app.bundleId ?? "")
        var s = "msu_begin \(id)\n"
        s += "\(attempt(app.source, app: app, team: sh(app.teamId ?? ""))); MSU_RC=$?\n"
        s += "if [ $MSU_RC -eq 0 ] || [ $MSU_RC -eq 3 ]; then\n"
        s += "  msu_ok \(id)\n"
        s += "  msu_receipt \(id) \(name) installed \"\" \(bundle)\n"
        if let fb = app.fallback {
            s += "elif \(attempt(fb, app: app, team: sh(app.teamId ?? ""))); then\n"
            s += "  msu_ok \(id) \"Installed via Homebrew\"\n"
            s += "  msu_receipt \(id) \(name) installed \"homebrew\" \(bundle)\n"
        }
        s += "else\n"
        s += "  msu_fail \(id)\n"
        s += "  msu_receipt \(id) \(name) failed \"$MSU_ERR\" \(bundle)\n"
        s += "fi\n"
        return s
    }

    // MARK: - Quoting

    /// Single-quote for bash, escaping embedded single quotes.
    static func sh(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
